# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6674f1f95dd0b8699b3e6e677b819ece"
name = "tiered-pricing"
application_url = "https://www.tieredpricingapp.online"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request" ]
  uri = "/webhooks/customers/data_request"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/redact" ]
  uri = "/webhooks/customers/redact"

  [[webhooks.subscriptions]]
  compliance_topics = [ "shop/redact" ]
  uri = "/webhooks/shop/redact"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_discounts,read_products,write_discounts"

[auth]
redirect_urls = [
  "https://www.tieredpricingapp.online/api/auth",
  "https://www.tieredpricingapp.online/api/auth/callback",
  "https://www.tieredpricingapp.online/auth/callback",
  "https://tiered-pricing-hazel.vercel.app/api/auth",
  "https://tiered-pricing-hazel.vercel.app/api/auth/callback",
  "https://tiered-pricing-hazel.vercel.app/auth/callback"
]
